// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(InscripciondbContext))]
    [Migration("20221013180802_eliminadodeMateriaCicloLectivo")]
    partial class eliminadodeMateriaCicloLectivo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Data.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("ApellidoNombre")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("Dni")
                        .HasColumnType("int(11)")
                        .HasColumnName("DNI");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id");

                    b.ToTable("alumno");
                });

            modelBuilder.Entity("Data.Models.Aniocarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CarreraId1")
                        .HasColumnType("int(11)")
                        .HasColumnName("Carrera_Id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CarreraId1" }, "fk_AnioCarrera_Carrera1_idx");

                    b.ToTable("aniocarrera");
                });

            modelBuilder.Entity("Data.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id");

                    b.ToTable("carrera");
                });

            modelBuilder.Entity("Data.Models.Ciclolectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id");

                    b.ToTable("ciclolectivo");
                });

            modelBuilder.Entity("Data.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CicloLectivoId")
                        .HasColumnType("int(11)");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CicloLectivoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("inscripcion");
                });

            modelBuilder.Entity("Data.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int?>("AnioCarreraId")
                        .HasColumnType("int(11)");

                    b.Property<int>("AnioCarreraId1")
                        .HasColumnType("int(11)")
                        .HasColumnName("AnioCarrera_Id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AnioCarreraId1" }, "fk_Materia_AnioCarrera1_idx");

                    b.ToTable("materia");
                });

            modelBuilder.Entity("Data.Models.Aniocarrera", b =>
                {
                    b.HasOne("Data.Models.Carrera", "CarreraId1Navigation")
                        .WithMany("Aniocarreras")
                        .HasForeignKey("CarreraId1")
                        .HasConstraintName("fk_AnioCarrera_Carrera1")
                        .IsRequired();

                    b.Navigation("CarreraId1Navigation");
                });

            modelBuilder.Entity("Data.Models.Inscripcion", b =>
                {
                    b.HasOne("Data.Models.Alumno", "Alumno")
                        .WithMany("Inscripcions")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Ciclolectivo", "CicloLectivo")
                        .WithMany()
                        .HasForeignKey("CicloLectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("CicloLectivo");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Data.Models.Materia", b =>
                {
                    b.HasOne("Data.Models.Aniocarrera", "AnioCarreraId1Navigation")
                        .WithMany("Materias")
                        .HasForeignKey("AnioCarreraId1")
                        .HasConstraintName("fk_Materia_AnioCarrera1")
                        .IsRequired();

                    b.Navigation("AnioCarreraId1Navigation");
                });

            modelBuilder.Entity("Data.Models.Alumno", b =>
                {
                    b.Navigation("Inscripcions");
                });

            modelBuilder.Entity("Data.Models.Aniocarrera", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Data.Models.Carrera", b =>
                {
                    b.Navigation("Aniocarreras");
                });
#pragma warning restore 612, 618
        }
    }
}
